# Generated by Django 3.1.4 on 2020-12-25 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('square_footage', models.PositiveIntegerField()),
                ('num_bedrooms', models.PositiveSmallIntegerField(verbose_name='Number of bedrooms')),
                ('num_bathrooms', models.PositiveSmallIntegerField(verbose_name='Number of bathrooms')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balcony', models.BooleanField(default=True, verbose_name='Has a balcony?')),
                ('laundry', models.CharField(choices=[('EN', 'Ensuite'), ('CO', 'Coin'), ('OF', 'Offsite')], default='EN', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('square_footage', models.PositiveIntegerField()),
                ('num_bedrooms', models.PositiveSmallIntegerField(verbose_name='Number of bedrooms')),
                ('num_bathrooms', models.PositiveSmallIntegerField(verbose_name='Number of bathrooms')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_stories', models.PositiveSmallIntegerField(verbose_name='Number of stories')),
                ('garage', models.CharField(choices=[('AT', 'Attached'), ('DT', 'Detached'), ('NO', 'None')], default='AT', max_length=2)),
                ('yard_fenced', models.BooleanField(default=True, verbose_name='Is the yard fenced?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
