# Generated by Django 3.1.4 on 2021-01-01 18:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='num_bathrooms',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Number of bathrooms'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='num_bedrooms',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Number of bedrooms'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='house',
            name='num_bathrooms',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Number of bathrooms'),
        ),
        migrations.AlterField(
            model_name='house',
            name='num_bedrooms',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Number of bedrooms'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
    ]
