# Generated by Django 3.1.4 on 2020-12-25 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='house',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
