# Generated by Django 3.1.4 on 2020-12-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20201225_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
