# Generated by Django 3.1.4 on 2020-12-31 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_apartment_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['-updated_on']},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-updated_on']},
        ),
    ]
